include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true

bloc:
  rules:
    - avoid_build_context_extensions
    - avoid_flutter_imports
    - avoid_public_bloc_methods
    - avoid_public_fields
    - prefer_file_naming_conventions
    - prefer_void_public_cubit_methods
analyzer:
  errors:
    unintended_html_in_doc_comment: ignore
