// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADiHT_aINol0TBsgXyVa8HY7tW1bJ0iw0',
    appId: '1:998190074728:web:2eb4536363fe37b9daa4dd',
    messagingSenderId: '998190074728',
    projectId: 'financo-13f01',
    authDomain: 'financo-13f01.firebaseapp.com',
    storageBucket: 'financo-13f01.firebasestorage.app',
    measurementId: 'G-7YKRC6ZZKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0aWbIRtqd3wk3MTx83q2LuITjWrKcJQY',
    appId: '1:998190074728:android:09e605d519606099daa4dd',
    messagingSenderId: '998190074728',
    projectId: 'financo-13f01',
    storageBucket: 'financo-13f01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDHnh9ph-YlKem6yZMpUuIlDFsrMWFZlo',
    appId: '1:998190074728:ios:86c595caa7b18bdcdaa4dd',
    messagingSenderId: '998190074728',
    projectId: 'financo-13f01',
    storageBucket: 'financo-13f01.firebasestorage.app',
    androidClientId: '998190074728-9enmdatgfl75ubk3omq5k9pnfjj7g1i4.apps.googleusercontent.com',
    iosClientId: '998190074728-dkce9gmuds1ohknffn3lo5euvcqsetgd.apps.googleusercontent.com',
    iosBundleId: 'com.example.financo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDHnh9ph-YlKem6yZMpUuIlDFsrMWFZlo',
    appId: '1:998190074728:ios:86c595caa7b18bdcdaa4dd',
    messagingSenderId: '998190074728',
    projectId: 'financo-13f01',
    storageBucket: 'financo-13f01.firebasestorage.app',
    androidClientId: '998190074728-9enmdatgfl75ubk3omq5k9pnfjj7g1i4.apps.googleusercontent.com',
    iosClientId: '998190074728-dkce9gmuds1ohknffn3lo5euvcqsetgd.apps.googleusercontent.com',
    iosBundleId: 'com.example.financo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADiHT_aINol0TBsgXyVa8HY7tW1bJ0iw0',
    appId: '1:998190074728:web:0edb28e8c46d7cfddaa4dd',
    messagingSenderId: '998190074728',
    projectId: 'financo-13f01',
    authDomain: 'financo-13f01.firebaseapp.com',
    storageBucket: 'financo-13f01.firebasestorage.app',
    measurementId: 'G-VVDZ2FN853',
  );
}
